name: "PR Slack Notification"
description: "A GitHub Action to notify Slack about pull request events."
author: "roseline124"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
  slack_token:
    description: "Slack Bot Token"
    required: true
  slack_channel:
    description: "Slack Channel ID"
    required: true
  slack_workspace:
    description: "Slack Workspace Name"
    required: true
  reviewers_file:
    description: "Path to the reviewers YAML file. default: reviewers.yml on project root level."
    required: false
    default: "reviewers.yml"
  slack_merge_emoji_name:
    description: "Emoji to attach to slack pr message"
    required: false
    default: "white_check_mark"
runs:
  using: "node20"
  main: "dist/index.js"
